
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies 📦
        run: npm ci

      - name: Build 🏗️
        run: npm run build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}

      # Ensure CNAME file exists with correct content
      - name: Create CNAME file 📄
        run: echo "eluvie.com" > dist/CNAME

      # Create a .nojekyll file to prevent GitHub Pages from ignoring files that begin with an underscore
      - name: Add .nojekyll file
        run: touch dist/.nojekyll

      # Add a special redirect script for SPA routing on GitHub Pages
      - name: Create 404.html for SPA routing
        run: |
          cp dist/index.html dist/404.html

      # Configure Git for deployment
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Deploy to GitHub Pages
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: true
          single-commit: true
          force: true
